# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CodeDepth with Ryan
email: ingyu.hwang91@gmail.com
name: "Ryan Ingyu Hwang"
author: "Ryan Ingyu Hwang"
description: CodeDepth with Ryan은 Ryan Ingyu Hwang의 블로그입니다. 머신러닝, 딥러닝, Flutter 앱 개발, 소프트웨어 프로젝트 관리를 탐구합니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryan-hwang-00.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RyanIngyuHwang
github_username: ryan-hwang-00

encoding: utf-8
locale: "en-KR"
show_date: true
date_format: "%Y-%m-%d"
comments: true
search: true

github: [metadata]

# paginate: 5 # amount of posts to show
# paginate_path: /page:num/

minimal_mistakes_skin: dirt

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      # read_time: true
      # comments: true
      share: true
      related: true
      author: "Ryan Ingyu Hwang"

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      # read_time: true
      # comments: true
      share: true
      related: true
      author: "Ryan Ingyu Hwang"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ingyu.hwang.91@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/RyanIngyuHwangs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ryan-hwang-00"


      # Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - .gitignore
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"